theme: jekyll-theme-primer
title: CS 109 Final Project
description: Project for Group 34 
baseurl: "/109final" 
markdown: kramdown 
kramdown:
    math_engine: mathjax
    input: GFM
    auto_ids: false
    syntax_highlighter: rouge
